Add Polish translations
smuggled-bits/AKME pull request #1
Opened 2023-05-18 17:46 UTC by DuckyBlender

Added Polish translations

2023-06-08 22:19 UTC, stanleyguevara requested changes
Mostly done with suggestions. Need some clarifications for context. Not sure if one should really translate some strictly technical terms like highlighted in the comments.

Maybe some stuff could be phrased a bit better, but that's just general issue of dealing with automated translations. Sometimes trying to fix it makes it feel even more auto-translated and the only way is to re-write the sentence completely. But as it is now should be super good enough :)

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"gettingStarted" = "Rozpoczęcie";
```suggestion
"gettingStarted" = "Wprowadzenie";
```
Rozpoczęcie is infinitive verb and it seems a bit weird if the context is header. Wprowadzenie (introduction) seems more appropriate.

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"titleJudgement" = "Bądź ostrożny i korzystaj z własnego rozsądku";
```suggestion
"titleJudgement" = "Bądź ostrożny i korzystaj z zdrowego rozsądku";
```

Zdrowego rozsądku is kinda more phraseologic - like "common sense"

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"textJudgement" = "\tAKME korzysta z GPT, dużego modelu językowego, który czasami może dostarczyć niepoprawne lub mylące informacje.\n\tZawsze korzystaj z własnego rozsądku i sprawdzaj informacje dos
```suggestion
"textJudgement" = "\tAKME korzysta z GPT, dużego modelu językowego, który czasami może dostarczyć niepoprawnych lub mylących informacji.\n\tZawsze korzystaj z własnego rozsądku i sprawdzaj informacje dostarczone przez aplikację, zanim podejmiesz decyzje na ich podstawie.";
```

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"continueLabel" = "\tKontynuuj";
```suggestion
"continueLabel" = "\tDalej";
```
Bit less convoluted and shorter - more like next or further in meaning

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"textPurchase" = "Ta opcja pozwala Ci na zakup tokenów bezpośrednio w aplikacji AKME, zapewniając płynne doświadczenie.\nTwoje wykorzystanie będzie odejmowane z salda Twoich tokenów w aplikacji. Gdy
```suggestion
"textPurchase" = "Ta opcja pozwala Ci na zakup tokenów bezpośrednio w aplikacji AKME, zapewniając płynne działanie.\nZużyte przez Ciebie tokeny będą odejmowane z salda Twoich tokenów w aplikacji. Gdy Twoje saldo spadnie do zera lub spadnie poniżej wymaganej liczby tokenów dla prompta możesz zakupić więcej tokenów, lub przełączyć się na opcję BYOK.\nNadal będziesz mieć dostęp do swoich istniejących wątków czatu, niezależnie od Twojego aktualnego salda tokenów.";
```

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"tokensExplanation" = "Tokeny są podstawowymi jednostkami tekstu, z którymi modele językowe pracują. Reprezentują one najmniejsze jednostki znaczeniowe i mogą być pojedynczymi znakami, całymi słowami
```suggestion
"tokensExplanation" = "Tokeny są podstawowymi jednostkami tekstu, z którymi modele językowe pracują. Reprezentują one najmniejsze jednostki znaczeniowe i mogą być pojedynczymi znakami, całymi słowami lub częściami słów. Modele językowe używają tych tokenów do zrozumienia i generowania tekstu, co czyni je niezbędnymi do ich funkcjonowania.\n\nW kontekście API, takiego jak OpenAI, tokeny odgrywają kluczową rolę w określaniu kosztów wykorzystania. Proces tokenizacji rozkłada zarówno prompt wejściowy, jak i wygenerowaną odpowiedź na tokeny. Całkowita liczba wykorzystanych tokenów wpływa na koszt, czas przetwarzania i ograniczenia API. Dlatego wysyłając prompt i otrzymując odpowiedź, tokeny są \"wydawane\", co oznacza, że użytkownicy są rozliczani na podstawie łącznej liczby tokenów użytych w prompcie i odpowiedzi. Ten mechanizm konsumpcji tokenów zachęca do ich efektywnego wykorzystania i zapewnia, że modele językowe skutecznie pracują z różnorodnymi danymi językowymi.";
```
Fakturowani has a strict meaning of VAT invoice, rozliczani is more like "charged"

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"balanceInfo" = "Ta informacja może nie uwzględniać zakupów lub wykorzystania z innych urządzeń połączonych z tym samym kontem.";
```suggestion
"balanceInfo" = "Ta lista nie uwzględnia zakupów lub wykorzystania z innych urządzeń połączonych z tym samym kontem.";
```
Informacja seems bit too generic. I'm assuming it's a list of some kind. Also "może nie uwzględniać" is in polish like "it might or it might not, you'll never know", which seems wrong, so I changed it to more definitive sounding "it doesn't take into account"

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"purchase" = "Kup";
Context needed, it means "Go buy" or "Do buy" as is

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"temperatureToolTip" = "Jaka temperatura próbkowania ma być używana,\nod 0 do 2.\n\nWyższe wartości, takie jak 0,8, sprawią, że wynik będzie bardziej losowy, podczas gdy niższe wartości, takie jak 0,
```suggestion
"temperatureToolTip" = "Jaka temperatura próbkowania ma być używana,\nod 0 do 2.\n\nWyższe wartości, takie jak 0,8, sprawią, że wynik będzie bardziej losowy, podczas gdy niższe wartości, takie jak 0,2, sprawią, że będzie bardziej ukierunkowany i deterministyczny.\n\nZalecamy zmianę tego lub top_p, ale nie obu jednocześnie.";
```

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"topPToolTip" = "Alternatywa dla próbkowania z użyciem temperatury, nazywana próbkowaniem \"nucleusa\", w której model rozważa wyniki tokenów z top_p masą prawdopodobieństwa.\n\nWięc 0,1 oznacza, że
```suggestion
"topPToolTip" = "Alternatywa dla próbkowania z użyciem temperatury, nazywana próbkowaniem jądra, w której model rozważa wyniki tokenów z masą prawdopodobieństwa top_p.\n\nZatem, 0,1 oznacza, że ​​rozważane są tylko tokeny stanowiące górne 10% masy prawdopodobieństwa.\n\nZalecamy zmianę tego lub temperatury, ale nie obu jednocześnie.";
```

Although, not sure about using "jądra" instead of nucleus. On one hand it's a broader issue of translating deep technical terms, on the other "jądro" is somewhat risky word, cause it also means a testicle ;)

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"maxTokensToolTip" = "Maksymalna liczba tokenów do wygenerowania podczas rozmowy.\n\nCałkowita długość tokenów wejściowych i wygenerowanych tokenów jest ograniczona przez długość kontekstu modelu.";
```suggestion
"maxTokensToolTip" = "Maksymalna liczba tokenów do wygenerowania podczas czatu.\n\nCałkowita długość tokenów prompta i odpowiedzi jest ograniczona przez długość kontekstu modelu.";
```
I'm assuming it's regarding prompt + answer tokens here

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"frequencyPenaltyToolTip" = "Liczba od -2,0 do 2,0.\n\nDodatnie wartości karzą nowe tokeny na podstawie ich istniejącej częstości w tekście do tej pory, zmniejszając prawdopodobieństwo, że model powt
```suggestion
"frequencyPenaltyToolTip" = "Liczba od -2,0 do 2,0.\n\nDodatnie wartości karzą nowe tokeny na podstawie ich częstości występowania w tekście do tej pory, zmniejszając prawdopodobieństwo, że model powtórzy ten sam wiersz dosłownie.";
```

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"exportLog" = "Eksportuj dziennik";
What log is that? Dziennik is more of diary than anything else. If that's saldo log then Eksportuj saldo, if that's like some technical log then Eksportuj logi

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"me" = "Ja";
Context?

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"instructionsDetail" = "Przed rozpoczęciem pracy, prosimy przeczytać poniższe ważne instrukcje, aby zapewnić najlepsze doświadczenie z AKME.";
```suggestion
"instructionsDetail" = "Przed rozpoczęciem prosimy przeczytać poniższe ważne instrukcje, aby zapewnić najlepsze doświadczenie z AKME.";
```

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"describeIssue" = "Proszę opisać problem, z którym się zmagasz.\nDołączono także dziennik ostatnich transakcji oraz kopię pliku konfiguracyjnego. Te pliki nie zawierają żadnych informacji identyfikuj
```suggestion
"describeIssue" = "Proszę opisać problem, z którym się zmagasz.\nDołączono także logi ostatnich transakcji oraz kopię pliku konfiguracyjnego. Te pliki nie zawierają żadnych informacji identyfikujących.\nProszę nie udostępniać poufnych lub prywatnych informacji.";
```

2023-06-08 22:19 UTC, stanleyguevara commented on pl.lproj/Localizable.strings
> +"retryRequest" = "Powtórzyć żądanie?";
```suggestion
"retryRequest" = "Powtórzyć zapytanie?";
```
Zapytanie is more like asking for something. Żądanie is more like strong demand.

2023-06-11 07:07 UTC, merged

2023-06-17 16:57 UTC, DuckyBlender commented
Oh, sorry for not answering, I didn't get any notifications for some reason

2023-06-27 09:24 UTC, stanleyguevara commented
No probs, glad I could help!